<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 *
 * @suxiaolin <dear.lin@live.com>
 */
return [
    'Bulk Actions' => '批量操作',
    'Please select one or more items from the list.' => '至少选择一项。',
    'General' => '常规',
    'Delete' => '删除',
    'Are you sure you want to delete these items?' => '确认删除?',
    'Create New' => '新增',
];
